# to tell that admin access is required.
sudo: required

# a docker container will be required.
services:
  - docker

before_install:
  - docker build -t ishantoberoi/docker-react -f Dockerfile.dev .

# Using the command with -e CI=true as there is some issue with jest
# we do not get the exit status 0 after the run test is completed.
script:
  - docker run -e CI=true ishantoberoi/docker-react npm run test

# app address http://dockerreact-env.eba-gbjmp2i6.us-east-2.elasticbeanstalk.com/
# AWS_ACCESS_KEY and AWS_SECRET_KEY configured in travis as environement
# variables https://travis-ci.org/github/oberoi-ishant/docker-react/settings
# for security reasons as our repository on github is public.
# app -> app name
# env -> app env name
# bucket_name -> aws - serives - s3 - name for your region elasticbeanstalk-us-east-2
# bucket_path: your app name in the bucket
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-041151477266"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY