# tutorial link https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11437116#questions
# Check yahoo mail with sub Docker react travis AWS details
# have some details in there. oberoiishant@yahoo.com
# This app is hosted on your personal github

# to tell that admin access is required.
sudo: required

# a docker container will be required.
services:
  - docker

before_install:
  - docker build -t ishantoberoi/docker-react -f Dockerfile.dev .

# Using the command with -e CI=true as there is some issue with jest
# we do not get the exit status 0 after the run test is completed.
script:
  - docker run -e CI=true ishantoberoi/docker-react npm run test

# Steps:
# 1. Login to aws
# 2. Create an elastic beanstalk application (web server)
# 3. Go to S3 bucket. find the elasticbeanstalk bucket for you region.
# like elasticbeanstalk-us-east-2-041151477266. Here you app folder will be created.
# So in config give bucket_path as you app name.
# 4. Go to IAM service. Create user with elasticbeanstalkfullaccess permission
# 5. Save the access_key_id and secret_access_key and add them as environment
# variables in travis ci. Use env variables with $ like $AWS_ACCESS_KEY below.


# app address http://docerreactapp-env.eba-dexmjzap.us-east-2.elasticbeanstalk.com/
# AWS_ACCESS_KEY and AWS_SECRET_KEY configured in travis as environement
# variables https://travis-ci.org/github/oberoi-ishant/docker-react/settings
# for security reasons as our repository on github is public.
# Below is how elasticbeanstalk page heading will look like on aws. From this:
# All Applications  docker-react-practice  DockerReactPractice-env  Environment ID: e-j2z5ypryvi, URL: DockerReactPractice-env.eba-fqmqj4rj.us-east-2.elasticbeanstalk.com
# app -> app name (docker-react-practice)
# env -> app env name (DockerReactPractice-env)
# bucket_name -> aws - serives - s3 - name for your region elasticbeanstalk-us-east-2
# bucket_path: your app name in the bucket
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-practice"
  env: "DockerReactPractice-env"
  bucket_name: "elasticbeanstalk-us-east-2-041151477266"
  bucket_path: "docker-react-practice"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY